title: PebblesEngine
email: Artur-Mamedbekov@yandex.ru
description: PebblesEngine
baseurl: ""
url: "https://pebblesengine.github.io"
github_username:  PebblesEngine
timezone: Europe/Moscow
language: ru

# Build settings
theme: minima
